xconnect:
  meta:
    # name for discovery
    name: account-service
    # tagged version of the implementation 
    version: v1.2.3
    # team that owns the code and operates it
    opex: team accounts
    tags:
      - account
      - registration
      - search    
  listen:
    api:     
      # public endpoint 
      host: where.grpc.can.be.reached
      protocol: grpc
      port: 443
    web:
      # public endpoint
      host: where.https.can.be.reached
      protocol: http
      tls: true
      port: 443
  connect:
    account-service-db:
      protocol: tcp 
      host: localhost 
      port: 5432
      url: jdbc:postgresql://localhost:5432/postgres?reWriteBatchedInserts=true
      kind: postgres
    account-service-cache:
      host: #REDIS_IP
      port: 6379
      kind: memorystore
    variant-publish:
      gcp.pubsub:
        topic: VariantToAssortment_Push_v1-topic   
        project: the-other-project       
    variant-pull:
      gcp.pubsub:
        subscription: Variant_v1-subscription
        test:
          topic: Variant_v1-topic